run:
    use_existing_run: "20200522_202539"  # Either False or the version string of the run to use.

    paths:
        extract: &extract "model_data/01_source"
        preprocess: &preprocess "model_data/02_preprocess"
        train: &train "model_data/03_train"
        test: &test "model_data/04_test"
        predict: &predict "model_data/05_predict"

    versioning:  # Ignored if use_existing_run is not False.
        module: "python_package.utils"
        name: "get_time_str"


task:

    extract:
        writer:
            module: "pandas"
            name: "DataFrame.to_csv"
            params:
                index: False
        output:
            path: *extract
            file: &extract_output "iris.csv"

    preprocess:
        input:
            path: *extract
            file: *extract_output
        loader:
            module: "pandas"
            name: "read_csv"
            params:
                sep: ","
        writer:
            module: "pandas"
            name: "DataFrame.to_parquet"
            params:
                index: False
        output:
            path: *preprocess
            file: &preprocess_output "pp_iris.parquet"

    train:
        target_col: "species"
        cols_to_ignore: ["sepal_width"]
        input:
            path: *preprocess
            file: *preprocess_output
        loader:
            module: "pandas"
            name: "read_parquet"
            params: {}
        writer:
            module: "pandas"
            name: "DataFrame.to_parquet"
            params:
                index: False
        split:
            module: "sklearn.model_selection"
            name: "train_test_split"
            params:
                test_size: 0.33
                random_state: 42
            output:
                path: *train
                file: &split_output "train_test.pkl"
        model:
            module: "sklearn.ensemble"
            name: "RandomForestClassifier"
            params:
                n_estimators: 1000
                max_depth: 5
                random_state: 42
                n_jobs: -1
            output:
                path: *train
                file: &model_output "model.pkl"

    test:
        input_model:
            path: *train
            file: *model_output
        input_split:
            path: *train
            file: *split_output
        loader:
            module: "pandas"
            name: "read_pickle"
            params: {}
        writer:
            module: "pandas"
            name: "DataFrame.to_csv"
            params:
                sep: ","
                index: False
        metrics:
            f1:
                module: "sklearn.metrics"
                name: "f1_score"
            accuracy:
                module: "sklearn.metrics"
                name: "accuracy_score"
        output:
            path: *test
            file: "test.csv"

    predict:
        predict_data:
            path: *extract
            file: "predict_sample.csv"
        model:
            path: *train
            file: *model_output
        output:
            path: *predict
            file: &predict_output "predict.csv"
